[package]
name = "p2p-node-handshake"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
rand = "0.9.1"
byteorder = "1.5.0"
sha2 = "0.10.9"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
tokio = { version = "1.38.0", features = ["full"] }
futures = "0.3.31"
